services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - 3000:3000
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - 8080:8080
